ospll check testin

diff --git a/.git_template/hooks/prepare-commit-msg b/.git_template/hooks/prepare-commit-msg
--- a/.git_template/hooks/prepare-commit-msg
+++ b/.git_template/hooks/prepare-commit-msg
@@ -5,10 +5,12 @@
 
 # codespell commit message
 
-
 printf "Spell check the commit message:\n $(cat $1) \n"
 codespell --ignore-words=ignore-spelling-words.txt $1
-if [ $? != 0 ]; then
+CMD_STATUS=$?
+echo "Status ${CMD_STATUS}"
+if [ ${CMD_STATUS} != 0 ]; then
+    printf "\033[0;31mError: Commit message failed spellcheck with a status of:\033[0m\n ${CMD_STATUS}"
     exit 1
 fi
 
